default_platform(:ios)

platform :ios do
  # https://docs.fastlane.tools/best-practices/continuous-integration/github/
  before_all do
    setup_ci if ENV["CI"]
  end

  desc "Run tests"
  lane :test do
    scan(
      package_path: './',
      destination: 'platform=iOS Simulator,name=iPhone 12',
      scheme: "BaseKit",
      code_coverage: true
    )
  end
end
