name: CI
on:
  push:
    branches: ['**']
jobs:
  build:
    name: Build/Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Authenticate private GitHub repos
        run: git config --global url."https://oauth2:${{ secrets.GH_ACCESS_TOKEN }}@github.com".insteadOf https://github.com
      - name: Configure Ruby dependencies cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install Ruby dependencies
        run: |
          bundle config path vendor/bundle
          bundle install
      - name: Test
        run: bundle exec fastlane test
  notify:
    name: Notify
    needs: [build]
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEVOPS_WEBHOOK_URL }}
    if: ${{ always() && env.SLACK_WEBHOOK_URL != null }}
    runs-on: ubuntu-latest
    steps:
      - uses: andrewscwei/slack-action@v1.0.0
        with:
          success: ${{ needs.build.result == 'success' && needs.deploy.result == 'success' }}
          webhook-url: ${{ env.SLACK_WEBHOOK_URL }}
