name: CI
on:
  push:
    branches: ['**']
env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
jobs:
  build:
    name: Build/Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Ruby dependencies
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install Ruby dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --path vendor/bundle
      - name: Test
        run: bundle exec fastlane test
