name: CI
on:
  push:
    branches: ['**']
jobs:
  build:
    name: Build/Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Ruby dependencies cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install Ruby dependencies
        run: |
          bundle config path vendor/bundle
          bundle install
      - name: Test
        run: bundle exec fastlane test
